export const initialSchemaSql = [
  `CREATE TABLE IF NOT EXISTS "user" (
    "id" text PRIMARY KEY NOT NULL,
    "name" text NOT NULL,
    "email" text NOT NULL UNIQUE,
    "email_verified" boolean NOT NULL,
    "image" text,
    "company" text,
    "created_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "session" (
    "id" text PRIMARY KEY NOT NULL,
    "expires_at" timestamp NOT NULL,
    "token" text NOT NULL UNIQUE,
    "created_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL,
    "ip_address" text,
    "user_agent" text,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade
  )`,
  `CREATE TABLE IF NOT EXISTS "account" (
    "id" text PRIMARY KEY NOT NULL,
    "account_id" text NOT NULL,
    "provider_id" text NOT NULL,
    "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade,
    "access_token" text,
    "refresh_token" text,
    "id_token" text,
    "access_token_expires_at" timestamp,
    "refresh_token_expires_at" timestamp,
    "scope" text,
    "password" text,
    "created_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "verification" (
    "id" text PRIMARY KEY NOT NULL,
    "identifier" text NOT NULL,
    "value" text NOT NULL,
    "expires_at" timestamp NOT NULL,
    "created_at" timestamp,
    "updated_at" timestamp
  )`,
  `CREATE TABLE IF NOT EXISTS "project" (
    "id" text PRIMARY KEY NOT NULL,
    "name" text NOT NULL,
    "slug" text NOT NULL UNIQUE,
    "region" text DEFAULT 'eu-west-2' NOT NULL,
    "owner_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade,
    "db_url" text,
    "storage_bucket" text,
    "plan" text DEFAULT 'starter' NOT NULL,
    "created_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "api_key" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "project"("id") ON DELETE cascade,
    "name" text NOT NULL,
    "key" text NOT NULL UNIQUE,
    "type" text DEFAULT 'anon' NOT NULL,
    "created_at" timestamp NOT NULL,
    "last_used_at" timestamp
  )`,
  `CREATE TABLE IF NOT EXISTS "project_log" (
    "id" text PRIMARY KEY NOT NULL,
    "project_id" text NOT NULL REFERENCES "project"("id") ON DELETE cascade,
    "service" text NOT NULL,
    "method" text NOT NULL,
    "path" text NOT NULL,
    "status" integer NOT NULL,
    "duration_ms" integer NOT NULL,
    "ip_address" text,
    "message" text,
    "created_at" timestamp NOT NULL
  )`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "name" text`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email" text`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email_verified" boolean DEFAULT false NOT NULL`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "image" text`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "company" text`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "expires_at" timestamp`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "token" text`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "ip_address" text`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "user_agent" text`,
  `ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "user_id" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "account_id" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "provider_id" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "user_id" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "access_token" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refresh_token" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "id_token" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "access_token_expires_at" timestamp`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "refresh_token_expires_at" timestamp`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "scope" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "password" text`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "service" text`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "method" text`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "path" text`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "status" integer`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "duration_ms" integer`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "ip_address" text`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "message" text`,
  `ALTER TABLE "project_log" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now() NOT NULL`,
];
